from __future__ import annotations

"""
/sync-github-actions slash command implementation.

Generates a ready-to-commit GitHub Actions workflow that runs HarnessSync
in CI whenever CLAUDE.md or .claude/ config changes. The generated workflow
opens a PR with translated config updates for each registered harness.

Modes:
  sync (default) — sync on push to main, open PR with translated configs
  gate           — check on PRs, FAIL if any harness config would drift
  pr             — PR-triggered dry-run workflow
  matrix         — matrix-strategy workflow testing each target independently

Usage:
    /sync-github-actions [--output PATH] [--branch NAME] [--scope SCOPE] [--mode sync|gate|pr|matrix]

Options:
    --output PATH     Write workflow to this path
    --branch NAME     Target branch for sync PRs (default: main)
    --scope SCOPE     Sync scope: user | project | all (default: all)
    --mode MODE       Workflow mode: sync (default), gate, pr, or matrix
    --dry-run         Print workflow YAML without writing file
"""

import os
import sys
import shlex
import argparse
from pathlib import Path

PLUGIN_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, PLUGIN_ROOT)

from src.adapters import AdapterRegistry
from src.ci_pipeline_generator import CIPipelineGenerator, CIPipelineConfig


_WORKFLOW_TEMPLATE = """\
# HarnessSync CI Workflow
# Generated by HarnessSync /sync-github-actions
# Runs whenever CLAUDE.md or .claude/ config changes and opens a PR
# with translated harness config updates.
#
# Prerequisites:
#   - Install HarnessSync in your dev environment or CI container
#   - Grant the workflow write permissions to open PRs (Settings > Actions > Workflow permissions)

name: Sync Harness Configs

on:
  push:
    branches: [{trigger_branch}]
    paths:
      - "CLAUDE.md"
      - ".claude/**"
      - ".harness-sync/**"
  workflow_dispatch:
    inputs:
      scope:
        description: "Sync scope (user | project | all)"
        required: false
        default: "{scope}"

permissions:
  contents: write
  pull-requests: write

jobs:
  harness-sync:
    name: Sync Claude Code → Harness Configs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install HarnessSync
        run: |
          pip install harness-sync 2>/dev/null || {{
            # Fall back to installing from source if not on PyPI
            pip install git+https://github.com/your-org/harnesssync.git 2>/dev/null || true
          }}

      - name: Run HarnessSync (dry-run first)
        id: dry_run
        run: |
          python -m src.commands.sync --scope {scope} --dry-run 2>&1 | tee /tmp/harness-sync-preview.txt
          echo "preview_lines=$(wc -l < /tmp/harness-sync-preview.txt)" >> "$GITHUB_OUTPUT"

      - name: Run HarnessSync
        run: python -m src.commands.sync --scope {scope}

      - name: Check for changes
        id: changes
        run: |
          git diff --quiet && echo "changed=false" >> "$GITHUB_OUTPUT" || echo "changed=true" >> "$GITHUB_OUTPUT"

      - name: Create sync branch and PR
        if: steps.changes.outputs.changed == 'true'
        env:
          GITHUB_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
        run: |
          BRANCH="harness-sync/auto-sync-${{{{ github.run_number }}}}"
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BRANCH"
          git add {sync_targets}
          git commit -m "chore(harness-sync): auto-sync from CLAUDE.md [skip ci]"
          git push origin "$BRANCH"

          # Build PR body from dry-run preview
          PREVIEW=$(head -50 /tmp/harness-sync-preview.txt)
          gh pr create \\
            --title "chore: auto-sync harness configs from CLAUDE.md" \\
            --body "## HarnessSync Auto-Sync

This PR was opened automatically by the HarnessSync CI workflow after detecting changes in CLAUDE.md or .claude/ configuration.

### Targets synced
{targets_list}

### Preview (first 50 lines)
\`\`\`
$PREVIEW
\`\`\`

---
*Auto-generated by [HarnessSync](https://github.com/your-org/harnesssync) · Close to skip this sync*" \\
            --base {trigger_branch} \\
            --head "$BRANCH" \\
            --label "harness-sync,automated"

      - name: No changes detected
        if: steps.changes.outputs.changed == 'false'
        run: echo "All harness configs are already up to date. No PR needed."
"""


_GATE_WORKFLOW_TEMPLATE = """\
# HarnessSync CI Drift Gate
# Generated by HarnessSync /sync-github-actions --mode gate
#
# Blocks PRs if CLAUDE.md changes would cause any harness config to drift.
# Fails the check so the PR author knows they must run /sync before merging.
#
# Prerequisites:
#   - Install HarnessSync in your dev environment or CI container
#   - The check runs in read-only mode — no files are written

name: Harness Config Drift Gate

on:
  pull_request:
    branches: [{trigger_branch}]
    paths:
      - "CLAUDE.md"
      - ".claude/**"
      - ".harness-sync/**"
      - "AGENTS.md"
      - "GEMINI.md"

permissions:
  contents: read
  pull-requests: write

jobs:
  drift-gate:
    name: Check Harness Config Drift
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install HarnessSync
        run: |
          pip install harness-sync 2>/dev/null || {{
            pip install git+https://github.com/your-org/harnesssync.git 2>/dev/null || true
          }}

      - name: Run drift check (dry-run)
        id: drift
        run: |
          set +e
          python -m src.commands.sync --scope {scope} --dry-run 2>&1 | tee /tmp/drift-report.txt
          CHANGED=$(grep -cE "^(\\+|\\-|Would write|Would update)" /tmp/drift-report.txt || echo "0")
          echo "changed_lines=$CHANGED" >> "$GITHUB_OUTPUT"
          echo "report_path=/tmp/drift-report.txt" >> "$GITHUB_OUTPUT"
          set -e

      - name: Post drift comment on PR
        if: steps.drift.outputs.changed_lines != '0'
        env:
          GITHUB_TOKEN: ${{{{ secrets.GITHUB_TOKEN }}}}
        run: |
          REPORT=$(head -80 /tmp/drift-report.txt)
          gh pr comment "${{{{ github.event.pull_request.number }}}}" --body "## ⚠️ HarnessSync Drift Detected

This PR modifies AI config files but the harness targets are out of sync.

**Run \`/sync\` in Claude Code and commit the updated harness files before merging.**

### Changes that would be applied
\`\`\`diff
$REPORT
\`\`\`

---
*HarnessSync drift gate — [learn more](https://github.com/your-org/harnesssync)*"

      - name: Fail if drift detected
        if: steps.drift.outputs.changed_lines != '0'
        run: |
          echo "FAIL: ${{{{ steps.drift.outputs.changed_lines }}}} harness config line(s) would change."
          echo "Run /sync in Claude Code to update harness configs, then commit and push."
          exit 1

      - name: All harness configs in sync
        if: steps.drift.outputs.changed_lines == '0'
        run: echo "✓ All harness configs are in sync with CLAUDE.md. No drift detected."
"""


def _build_targets_list(targets: list[str]) -> str:
    return "\n".join(f"- `{t}`" for t in targets)


def _build_sync_targets_glob(targets: list[str]) -> str:
    """Build git add pattern covering all harness config files."""
    patterns = []
    target_files = {
        "codex": "AGENTS.md .agents/",
        "gemini": "GEMINI.md .gemini/",
        "opencode": "opencode.json .opencode/",
        "cursor": ".cursor/",
        "aider": "CONVENTIONS.md .aider.conf.yml",
        "windsurf": ".windsurfrules .windsurf/",
        "vscode": ".github/copilot-instructions.md .codeium/",
    }
    for t in targets:
        if t in target_files:
            patterns.append(target_files[t])
    return " ".join(patterns) if patterns else "."


def generate_workflow(
    targets: list[str],
    trigger_branch: str = "main",
    scope: str = "all",
) -> str:
    """Generate GitHub Actions sync workflow YAML string.

    Args:
        targets: List of registered target names to include.
        trigger_branch: Branch that triggers the workflow.
        scope: Sync scope (user/project/all).

    Returns:
        YAML string for the workflow file.
    """
    return _WORKFLOW_TEMPLATE.format(
        trigger_branch=trigger_branch,
        scope=scope,
        targets_list=_build_targets_list(targets),
        sync_targets=_build_sync_targets_glob(targets),
    )


def generate_gate_workflow(
    trigger_branch: str = "main",
    scope: str = "all",
) -> str:
    """Generate a CI drift-gate workflow YAML string.

    The gate workflow triggers on pull_request events and fails if any
    harness config would change after syncing, enforcing that CLAUDE.md
    changes are always accompanied by updated target configs.

    Args:
        trigger_branch: Target branch for PRs to gate on.
        scope: Sync scope (user/project/all).

    Returns:
        YAML string for the gate workflow file.
    """
    return _GATE_WORKFLOW_TEMPLATE.format(
        trigger_branch=trigger_branch,
        scope=scope,
    )


def main(args: list[str] | None = None) -> int:
    """Entry point for /sync-github-actions command.

    Args:
        args: Command-line arguments (defaults to sys.argv[1:]).

    Returns:
        Exit code (0 = success).
    """
    parser = argparse.ArgumentParser(
        prog="sync-github-actions",
        description="Generate a GitHub Actions workflow for automated HarnessSync CI",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help="Output path for the workflow file",
    )
    parser.add_argument(
        "--branch",
        default="main",
        help="Branch that triggers the workflow (default: main)",
    )
    parser.add_argument(
        "--scope",
        default="all",
        choices=["user", "project", "all"],
        help="Sync scope (default: all)",
    )
    parser.add_argument(
        "--mode",
        default="sync",
        choices=["sync", "gate", "pr", "matrix"],
        help=(
            "Workflow mode: 'sync' opens a PR with updated configs on push (default); "
            "'gate' blocks PRs that would cause harness config drift; "
            "'pr' generates a PR-triggered dry-run workflow; "
            "'matrix' generates a matrix-strategy workflow testing each target independently"
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print workflow YAML without writing file",
    )

    parsed = parser.parse_args(args if args is not None else sys.argv[1:])

    targets = AdapterRegistry.list_targets()

    if parsed.mode == "pr":
        generator = CIPipelineGenerator.for_pr_trigger(base_branch=parsed.branch)
        workflow_yaml = generator.generate()
        default_output = Path(".github/workflows/harness-sync-pr.yml")
        mode_label = "PR trigger"
    elif parsed.mode == "matrix":
        generator = CIPipelineGenerator.for_matrix_trigger(targets=targets)
        workflow_yaml = generator.generate()
        default_output = Path(".github/workflows/harness-sync-matrix.yml")
        mode_label = "matrix trigger"
    elif parsed.mode == "gate":
        workflow_yaml = generate_gate_workflow(
            trigger_branch=parsed.branch,
            scope=parsed.scope,
        )
        default_output = Path(".github/workflows/harness-sync-gate.yml")
        mode_label = "drift gate"
    else:
        workflow_yaml = generate_workflow(
            targets=targets,
            trigger_branch=parsed.branch,
            scope=parsed.scope,
        )
        default_output = Path(".github/workflows/harness-sync.yml")
        mode_label = "sync"

    if parsed.dry_run:
        print(workflow_yaml)
        return 0

    # Write workflow file
    output_path: Path = parsed.output if parsed.output is not None else default_output
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(workflow_yaml, encoding="utf-8")

    print(f"GitHub Actions {mode_label} workflow written to: {output_path}")
    print()
    print("Next steps:")
    if parsed.mode == "pr":
        print(f"  1. Commit the workflow: git add {output_path}")
        print("  2. The workflow will run a dry-run sync on every PR")
    elif parsed.mode == "matrix":
        print(f"  1. Commit the workflow: git add {output_path}")
        print("  2. The workflow will test each target independently via matrix strategy")
        print(f"  Targets included: {', '.join(targets)}")
    elif parsed.mode == "gate":
        print("  1. Commit the workflow: git add .github/workflows/harness-sync-gate.yml")
        print("  2. The gate will block PRs that modify CLAUDE.md without updating harness configs")
        print("  3. Reviewers will see a comment with the drift diff when the gate fails")
    else:
        print("  1. Review the generated workflow and update the HarnessSync install step")
        print("  2. Grant Actions write permissions in Settings > Actions > Workflow permissions")
        print(f"  3. Commit: git add {output_path} && git commit -m 'ci: add harness-sync workflow'")
        print()
        print(f"Targets included: {', '.join(targets)}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
