from __future__ import annotations

"""Harness-Native Config Preview — render target config before sync.

For each target harness, this module renders a preview of exactly what
the target config files would contain after sync — without writing anything.

Users who care about native format correctness can verify HarnessSync's
translation output before it lands. Builds confidence and catches
translation issues (bad TOML, malformed JSON, wrong section headers).

Supported preview targets:
- codex:    AGENTS.md (with HarnessSync markers), .codex/config.toml
- gemini:   GEMINI.md, .gemini/settings.json
- opencode: AGENTS.md, opencode.json
- cursor:   .cursor/rules/harnesssync.mdc, .cursor/mcp.json
- aider:    CONVENTIONS.md, .aider.conf.yml
- windsurf: .windsurfrules, .windsurf/ (memory files)

The preview is generated by running adapters in a dry-run mode on a
temporary in-memory file system, then reading back what they would write.
"""

import json
import re
import tempfile
from pathlib import Path


# ──────────────────────────────────────────────────────────────────────────────
# Marker constants (must match what adapters use)
# ──────────────────────────────────────────────────────────────────────────────

_MANAGED_START = "<!-- Managed by HarnessSync -->"
_MANAGED_END = "<!-- End HarnessSync managed content -->"
_TIMESTAMP_PLACEHOLDER = "2026-01-01T00:00:00Z"  # Stable timestamp for preview


def _render_managed_md_section(rules_content: str, label: str = "rules") -> str:
    """Render a HarnessSync-managed section for Markdown-based targets.

    Args:
        rules_content: Rules text to embed.
        label: Target label for comment (e.g. "AGENTS.md for codex").

    Returns:
        Full managed section string with markers.
    """
    return (
        f"{_MANAGED_START}\n"
        f"<!-- Last synced: {_TIMESTAMP_PLACEHOLDER} | Label: {label} -->\n\n"
        f"{rules_content.strip()}\n\n"
        f"{_MANAGED_END}\n"
    )


def _render_codex_agents_md(rules_content: str, existing_content: str = "") -> str:
    """Render AGENTS.md as Codex would receive it.

    Args:
        rules_content: Source rules text.
        existing_content: Current AGENTS.md content (user's custom content preserved above).

    Returns:
        Full AGENTS.md content string.
    """
    managed = _render_managed_md_section(rules_content, "AGENTS.md")

    if existing_content:
        # Strip any existing managed section
        pattern = re.compile(
            re.escape(_MANAGED_START) + r".*?" + re.escape(_MANAGED_END) + r"\n?",
            re.DOTALL,
        )
        user_content = pattern.sub("", existing_content).rstrip()
        if user_content:
            return user_content + "\n\n" + managed
    return managed


def _render_codex_config_toml(mcp_servers: dict, settings: dict) -> str:
    """Render Codex config.toml content.

    Args:
        mcp_servers: MCP server config dict.
        settings: Settings dict (approval_mode, etc.).

    Returns:
        TOML-formatted config string.
    """
    lines = ["# HarnessSync generated — do not edit directly", ""]

    approval = settings.get("approval_mode", "auto")
    policy_map = {"auto": "on-failure", "suggest": "on-request", "ask": "on-request"}
    policy = policy_map.get(approval, "on-request")
    lines.append(f'approval_policy = "{policy}"')
    lines.append("")

    if mcp_servers:
        lines.append("[mcp_servers]")
        for name, cfg in sorted(mcp_servers.items()):
            lines.append(f"\n  [{name}]")
            if "command" in cfg:
                cmd = cfg["command"]
                if isinstance(cmd, list):
                    args = cmd[1:] if len(cmd) > 1 else []
                    cmd = cmd[0]
                    lines.append(f'  command = "{cmd}"')
                    if args:
                        args_str = ", ".join(f'"{a}"' for a in args)
                        lines.append(f"  args = [{args_str}]")
                else:
                    lines.append(f'  command = "{cmd}"')
                if "args" in cfg and isinstance(cfg["args"], list):
                    args_str = ", ".join(f'"{a}"' for a in cfg["args"])
                    lines.append(f"  args = [{args_str}]")
                if "env" in cfg and isinstance(cfg["env"], dict):
                    for k, v in cfg["env"].items():
                        lines.append(f'  env.{k} = "{v}"')
            elif "url" in cfg:
                lines.append(f'  url = "{cfg["url"]}"')
                if cfg.get("type"):
                    lines.append(f'  type = "{cfg["type"]}"')

    return "\n".join(lines) + "\n"


def _render_gemini_md(rules_content: str) -> str:
    """Render GEMINI.md as Gemini CLI would receive it."""
    return _render_managed_md_section(rules_content, "GEMINI.md")


def _render_gemini_settings_json(mcp_servers: dict, settings: dict) -> str:
    """Render .gemini/settings.json content."""
    output: dict = {}

    # Map settings
    allowed = settings.get("permissions", {}).get("allow", [])
    denied = settings.get("permissions", {}).get("deny", [])
    if allowed:
        output["tools"] = {"allowed": allowed}
    if denied:
        output.setdefault("tools", {})["exclude"] = denied

    # Add MCP servers
    if mcp_servers:
        output["mcpServers"] = {}
        for name, cfg in sorted(mcp_servers.items()):
            output["mcpServers"][name] = cfg

    return json.dumps(output, indent=2, ensure_ascii=False) + "\n"


def _render_opencode_agents_md(rules_content: str) -> str:
    """Render AGENTS.md for OpenCode."""
    return _render_managed_md_section(rules_content, "AGENTS.md for opencode")


def _render_cursor_mdc(rules_content: str) -> str:
    """Render .cursor/rules/harnesssync.mdc content."""
    frontmatter = (
        "---\n"
        "description: Synced from Claude Code via HarnessSync\n"
        "alwaysApply: true\n"
        "---\n\n"
    )
    return frontmatter + rules_content.strip() + "\n"


def _render_cursor_mcp_json(mcp_servers: dict) -> str:
    """Render .cursor/mcp.json content."""
    output = {"mcpServers": {}}
    for name, cfg in sorted(mcp_servers.items()):
        output["mcpServers"][name] = cfg
    return json.dumps(output, indent=2, ensure_ascii=False) + "\n"


def _render_aider_conventions_md(rules_content: str) -> str:
    """Render CONVENTIONS.md as Aider would receive it."""
    managed = (
        "<!-- HarnessSync: DO NOT EDIT — synced from CLAUDE.md -->\n\n"
        + rules_content.strip()
        + "\n\n<!-- End HarnessSync -->\n"
    )
    return managed


def _render_aider_conf_yml(settings: dict) -> str:
    """Render basic .aider.conf.yml content."""
    lines = ["# HarnessSync generated", ""]
    # Map relevant settings
    if settings.get("approval_mode"):
        lines.append(f"# approval_mode: {settings['approval_mode']} (aider uses --yes-always flag)")
    lines.append("# Add per-project settings below")
    return "\n".join(lines) + "\n"


def _render_windsurf_rules(rules_content: str) -> str:
    """Render .windsurfrules content."""
    return (
        "# Synced from Claude Code via HarnessSync\n"
        "# Do not edit — changes will be overwritten on next sync\n\n"
        + rules_content.strip()
        + "\n"
    )


# ──────────────────────────────────────────────────────────────────────────────
# Main preview generator
# ──────────────────────────────────────────────────────────────────────────────

_FILE_RENDERERS: dict[str, dict[str, object]] = {
    "codex": {
        "AGENTS.md": _render_codex_agents_md,
        ".codex/config.toml": _render_codex_config_toml,
    },
    "gemini": {
        "GEMINI.md": _render_gemini_md,
        ".gemini/settings.json": _render_gemini_settings_json,
    },
    "opencode": {
        "AGENTS.md": _render_opencode_agents_md,
    },
    "cursor": {
        ".cursor/rules/harnesssync.mdc": _render_cursor_mdc,
        ".cursor/mcp.json": _render_cursor_mcp_json,
    },
    "aider": {
        "CONVENTIONS.md": _render_aider_conventions_md,
        ".aider.conf.yml": _render_aider_conf_yml,
    },
    "windsurf": {
        ".windsurfrules": _render_windsurf_rules,
    },
}


def render_native_preview(
    harness: str,
    rules_content: str = "",
    mcp_servers: dict | None = None,
    settings: dict | None = None,
    existing_files: dict[str, str] | None = None,
) -> dict[str, str]:
    """Render native-format preview for a target harness.

    Args:
        harness: Target harness name (e.g. "codex", "gemini").
        rules_content: Source rules text from CLAUDE.md.
        mcp_servers: MCP server config dict.
        settings: Settings dict.
        existing_files: Current target file contents (for preserving user content).
                        Maps relative path -> content string.

    Returns:
        Dict mapping relative file path -> rendered content string.
        E.g. {"AGENTS.md": "...", ".codex/config.toml": "..."}
    """
    mcp_servers = mcp_servers or {}
    settings = settings or {}
    existing_files = existing_files or {}

    renderers = _FILE_RENDERERS.get(harness, {})
    result: dict[str, str] = {}

    for file_path, renderer in renderers.items():
        existing = existing_files.get(file_path, "")
        try:
            # Different renderers have different signatures
            if file_path.endswith(".toml") or file_path.endswith(".json"):
                # Pass mcp + settings
                content = renderer(mcp_servers, settings)  # type: ignore[call-arg]
            elif "mcp" in file_path:
                content = renderer(mcp_servers)  # type: ignore[call-arg]
            elif "conf.yml" in file_path:
                content = renderer(settings)  # type: ignore[call-arg]
            elif existing:
                content = renderer(rules_content, existing)  # type: ignore[call-arg]
            else:
                content = renderer(rules_content)  # type: ignore[call-arg]
        except Exception as e:
            content = f"[Preview error for {file_path}: {e}]"

        result[file_path] = content

    return result


def format_native_preview(
    harness: str,
    previews: dict[str, str],
    max_lines_per_file: int = 40,
) -> str:
    """Format native previews for display.

    Args:
        harness: Target harness name.
        previews: Output of render_native_preview().
        max_lines_per_file: Truncate preview at this many lines.

    Returns:
        Multi-line formatted preview string.
    """
    if not previews:
        return f"No preview available for harness: {harness}"

    lines = [
        f"Native Config Preview — {harness}",
        "=" * 50,
        "",
    ]

    for file_path, content in sorted(previews.items()):
        lines.append(f"[ {file_path} ]")
        content_lines = content.splitlines()
        if len(content_lines) > max_lines_per_file:
            display_lines = content_lines[:max_lines_per_file]
            lines.extend(display_lines)
            lines.append(f"  ... ({len(content_lines) - max_lines_per_file} more lines)")
        else:
            lines.extend(content_lines)
        lines.append("")

    return "\n".join(lines)


def get_all_native_previews(
    rules_content: str = "",
    mcp_servers: dict | None = None,
    settings: dict | None = None,
    harnesses: list[str] | None = None,
) -> dict[str, dict[str, str]]:
    """Generate native previews for all (or specified) harnesses.

    Args:
        rules_content: Source rules text.
        mcp_servers: MCP server config.
        settings: Settings dict.
        harnesses: Which harnesses to preview (default: all with renderers).

    Returns:
        Dict mapping harness name -> {file_path: content}.
    """
    target_harnesses = harnesses or list(_FILE_RENDERERS.keys())
    result: dict[str, dict[str, str]] = {}

    for harness in target_harnesses:
        result[harness] = render_native_preview(
            harness=harness,
            rules_content=rules_content,
            mcp_servers=mcp_servers,
            settings=settings,
        )

    return result
